const actionTypes = {
  USER_LOADING: 'USER_LOADING',
  USER_LOADING_SUCCESS: 'USER_LOADING_SUCCESS',
  USER_LOADING_FAILED: 'USER_LOADING_FAILED',

  USER_REGISTERING: 'USER_REGISTERING',
  USER_REGISTERING_SUCCESS: 'USER_REGISTERING_SUCCESS',
  USER_REGISTERING_FAILED: 'USER_REGISTERING_FAILED'
};

export default actionTypes;
