const actionTypes = {
  SIGUP_AND_LOGIN: 'SIGNUP_AND_LOGIN',

  AUTHENTICATION_WITH_TOKEN_SUCCESS: 'AUTHENTICATION_WITH_TOKEN_SUCCESS',
  AUTHENTICATION_WITH_TOKEN_FAILED: 'AUTHENTICATION_WITH_TOKEN_FAILED',

  USER_LOADING: 'USER_LOADING',
  USER_LOADING_SUCCESS: 'USER_LOADING_SUCCESS',
  USER_LOADING_FAILED: 'USER_LOADING_FAILED'
};

export default actionTypes;
