const actionTypes = {
  CONNECTION_TO_SOCKET_SUCCESS: 'CONNECTION_TO_SOCKET_SUCCESS',
  CONNECTION_TO_SOCKET_FAILED: 'CONNECTION_TO_SOCKET_FAILED',

  NEW_CONTACT: 'NEW_CONTACT',
  CONTACT_ONLINE: 'CONTACT_ONLINE',
  CONTACT_OFFLINE: 'CONTACT_OFFLINE',

  SOCKET_ERROR: 'error'
};

export default actionTypes;
