const actionTypes = {
  CONNECTION_TO_SOCKET_SUCCESS: 'CONNECTION_TO_SOCKET_SUCCESS',
  CONNECTION_TO_SOCKET_FAILED: 'CONNECTION_TO_SOCKET_FAILED',

  NEW_CONTACT: 'NEW_CONTACT',
  CONTACT_UPDATE: 'CONTACT_UPDATE',

  UPLOAD_PICTURE_SUCCESS: 'UPLOAD_PICTURE_SUCCESS',
  UPLOAD_PICTURE_FAILED: 'UPLOAD_PICTURE_FAILED',
  CHANGE_NAME_SUCCESS: 'CHANGE_NAME_SUCCESS',
  CHANGE_NAME_FAILED: 'CHANGE_NAME_FAILED',

  SOCKET_ERROR: 'error'
};

export default actionTypes;
